### ISSUE TITLE
Adventure no retired toshis info

### ISSUE THREAD

**Issue by iankarasz** [NiceNux/Toshi#28]
Problem: Users shouldnt be able to access the adventure scene when they don't have any retired toshis as they wouldnt be able to do anything and it may confuse them.

***

Proposed Solution: When someone goes to click the adventure scene but have no retired toshis they shouldnt be allowed to enter and a panel alerting them that they need retired toshis and how to get them will pop up.

**Comment by drewmaclean** [comment]
Collab commit 90
